server:
  port: 8000
  
spring:
  cloud:
    gatewary:
      routes:
        - id: test_router
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        
        - id: qq_router
          uri: https://www.qq.com
          predicates:
            - Query=url, qq

        
